#!/usr/bin/env python3
"""Generate the repo's cross-project code registry.

The registry covers reusable or reusable-looking code under investigation,
experiment, pipeline, tool, and shared-lib locations so a delegated duplicate-
check can search one inventory before writing a new script.
"""
from __future__ import annotations

import argparse
import ast
import os
import re
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.dev.generate_scripts_registry import (
    EXCLUDED_DIR_NAMES,
    SCRIPT_EXTENSIONS,
    extract_purpose,
)

SCRIPT_SCOPES = (
    "investigations",
    "experiments",
    "src/pipelines",
    "src/tools",
)
SHARED_LIB_ROOT = Path("src/lib")
__all__ = [
    "SCRIPT_SCOPES",
    "SHARED_LIB_ROOT",
    "build_registry",
    "find_script_paths",
    "find_shared_modules",
    "main",
]


def find_script_paths(root: Path) -> list[Path]:
    """Return sorted script paths in the configured cross-project locations."""
    found: list[Path] = []
    for scope in SCRIPT_SCOPES:
        base_dir = root / scope
        if not base_dir.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base_dir):
            dirnames[:] = sorted(d for d in dirnames if d not in EXCLUDED_DIR_NAMES)
            for filename in sorted(filenames):
                path = Path(dirpath) / filename
                if path.suffix in SCRIPT_EXTENSIONS:
                    found.append(path.relative_to(root))
    return sorted(found)


def find_shared_modules(root: Path) -> list[Path]:
    """Return sorted `src/lib/*` module directories."""
    lib_root = root / SHARED_LIB_ROOT
    if not lib_root.is_dir():
        return []
    modules = [path.relative_to(root) for path in sorted(lib_root.iterdir()) if path.is_dir() and path.name not in EXCLUDED_DIR_NAMES]
    return modules


def build_registry(root: Path) -> str:
    """Build the full markdown registry text for `root`."""
    scripts = find_script_paths(root)
    modules = find_shared_modules(root)
    lines = [
        "# Code Registry",
        "",
        "Auto-generated by `scripts/dev/generate_code_registry.py` — do not hand-edit; regenerate it instead.",
        "",
        "## Scripts",
        "",
        "| Code | Symbols | Purpose |",
        "|---|---|---|",
        *_build_script_rows(root, scripts),
        "",
        "## Shared modules",
        "",
        "| Module | Symbols | Purpose |",
        "|---|---|---|",
        *_build_module_rows(root, modules),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Write `CODE_REGISTRY.md` for the chosen repo root."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root to scan (default: this file's repo root).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Registry output path (default: <root>/CODE_REGISTRY.md).",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    out_path = args.out.resolve() if args.out is not None else root / "CODE_REGISTRY.md"
    out_path.write_text(build_registry(root), encoding="utf-8")
    print(out_path)


def _build_script_rows(root: Path, paths: list[Path]) -> list[str]:
    rows = [_script_row(root, path) for path in paths]
    return rows or ["| — | — | — |"]


def _build_module_rows(root: Path, paths: list[Path]) -> list[str]:
    rows = [_module_row(root, path) for path in paths]
    return rows or ["| — | — | — |"]


def _script_row(root: Path, path: Path) -> str:
    symbols = _format_symbols(_extract_symbols(root / path))
    purpose = extract_purpose(root / path) or "—"
    return f"| `{_escape_table(str(path))}` | {symbols} | {_escape_table(purpose)} |"


def _module_row(root: Path, path: Path) -> str:
    symbols = _format_symbols(_extract_module_symbols(root / path))
    purpose = _extract_module_purpose(root / path) or "—"
    return f"| `{_escape_table(str(path))}` | {symbols} | {_escape_table(purpose)} |"


def _extract_module_purpose(path: Path) -> str | None:
    init_file = path / "__init__.py"
    if init_file.is_file():
        purpose = extract_purpose(init_file)
        if purpose:
            return purpose
    for module_file in sorted(path.rglob("*.py")):
        if module_file.name == "__init__.py":
            continue
        purpose = extract_purpose(module_file)
        if purpose:
            return purpose
    return None


def _extract_module_symbols(path: Path) -> list[str]:
    symbols: set[str] = set()
    for module_file in sorted(path.rglob("*.py")):
        symbols.update(_extract_symbols(module_file))
    return sorted(symbols)


def _extract_symbols(path: Path) -> list[str]:
    if path.suffix == ".py":
        return _extract_python_symbols(path)
    if path.suffix == ".sh":
        return _extract_shell_symbols(path)
    return []


def _extract_python_symbols(path: Path) -> list[str]:
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    return [node.name for node in module.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]


def _extract_shell_symbols(path: Path) -> list[str]:
    content = path.read_text(encoding="utf-8")
    pattern = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*\(\)\s*\{", re.MULTILINE)
    return pattern.findall(content)


def _format_symbols(symbols: list[str]) -> str:
    if not symbols:
        return "—"
    return ", ".join(f"`{_escape_table(symbol)}`" for symbol in symbols)


def _escape_table(text: str) -> str:
    return text.replace("|", r"\|")


if __name__ == "__main__":
    main()
