#!/usr/bin/env python3
"""Generate the repo's script registry.

The registry covers committed, reusable scripts under ``scripts/`` plus still-unpromoted
scratch probes under ``scratch/``. ``scratch/`` entries keep their filename date so an
operator can quickly tell whether an older probe already answered today's question.
"""
from __future__ import annotations

import argparse
import ast
import os
import re
from pathlib import Path

EXCLUDED_DIR_NAMES = frozenset({".git", ".venv", "__pycache__", "node_modules"})
SCRIPT_EXTENSIONS = frozenset({".py", ".sh"})
# Shared with promote_scratch_scripts.py so both scripts agree on what counts as promotable code.
SCRATCH_DATE_RE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})_")


def find_scripts(root: Path, subdir: str) -> list[Path]:
    """Return sorted script paths under ``subdir``, relative to ``root``."""
    base_dir = root / subdir
    if not base_dir.is_dir():
        return []

    found: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(base_dir):
        dirnames[:] = sorted(d for d in dirnames if d not in EXCLUDED_DIR_NAMES)
        for filename in sorted(filenames):
            path = Path(dirpath) / filename
            if path.suffix in SCRIPT_EXTENSIONS:
                found.append(path.relative_to(root))
    return sorted(found)


def extract_purpose(path: Path) -> str | None:
    """Return the file's one-line purpose, or ``None`` when none is discoverable."""
    if path.suffix == ".py":
        return _extract_python_purpose(path)
    if path.suffix == ".sh":
        return _extract_shell_purpose(path)
    return None


def extract_scratch_date(path: Path) -> str | None:
    """Return the leading ``YYYY-MM-DD`` from a scratch filename, if present."""
    if path.parts[:1] != ("scratch",):
        return None
    match = SCRATCH_DATE_RE.match(path.name)
    return None if match is None else match.group("date")


def build_registry(root: Path) -> str:
    """Build the full markdown registry text for ``root``."""
    scripts = find_scripts(root, "scripts")
    scratch = find_scripts(root, "scratch")
    lines = [
        "# Script Registry",
        "",
        "Auto-generated by `scripts/dev/generate_scripts_registry.py` — do not hand-edit; regenerate it instead.",
        "",
        "## Scripts",
        "",
        "| Script | Purpose |",
        "|---|---|",
        *_build_script_rows(root, scripts),
        "",
        "## Scratch (unpromoted — check here before writing a new one)",
        "",
        "| Script | Date | Purpose |",
        "|---|---|---|",
        *_build_scratch_rows(root, scratch),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Write ``SCRIPTS.md`` for the chosen repo root."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root to scan (default: this file's repo root).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Registry output path (default: <root>/SCRIPTS.md).",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    out_path = args.out.resolve() if args.out is not None else root / "SCRIPTS.md"
    out_path.write_text(build_registry(root), encoding="utf-8")
    print(out_path)


def _build_script_rows(root: Path, paths: list[Path]) -> list[str]:
    rows = [_script_row(root, path) for path in paths]
    return rows or ["| — | — |"]


def _build_scratch_rows(root: Path, paths: list[Path]) -> list[str]:
    rows = [_scratch_row(root, path) for path in paths]
    return rows or ["| — | — | — |"]


def _script_row(root: Path, path: Path) -> str:
    purpose = extract_purpose(root / path) or "—"
    return f"| `{_escape_table(str(path))}` | {_escape_table(purpose)} |"


def _scratch_row(root: Path, path: Path) -> str:
    date = extract_scratch_date(path) or "—"
    purpose = extract_purpose(root / path) or "—"
    return f"| `{_escape_table(str(path))}` | {date} | {_escape_table(purpose)} |"


def _extract_python_purpose(path: Path) -> str | None:
    source = path.read_text(encoding="utf-8")
    module = ast.parse(source, filename=str(path))
    docstring = ast.get_docstring(module, clean=False)
    if not docstring:
        return None
    for line in docstring.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return None


def _extract_shell_purpose(path: Path) -> str | None:
    lines = path.read_text(encoding="utf-8").splitlines()
    start_idx = 1 if lines and lines[0].startswith("#!") else 0
    for line in lines[start_idx:]:
        if not line.strip():
            continue
        if line.startswith("# "):
            purpose = line[2:].strip()
            if purpose and not purpose.startswith("shellcheck "):
                return purpose
            continue
        if line.startswith("#"):
            continue
        break
    return None


def _escape_table(text: str) -> str:
    return text.replace("|", r"\|")


if __name__ == "__main__":
    main()
